name: LocalInGlobal

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          D:\\a\\Innocent-Eu4-mod\\Innocent-Eu4-mod\\.scripts\\LIGParser.exe
